name: vic-uni-book
recipe: drupal9
config:
  php: '8.0'
  composer_version: 2
  via: 'apache:2.4'
  webroot: web
  database: 'mysql:5.7'
  drush: true
  xdebug: false
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://vic-uni-book.lndo.site"
proxy:
  appserver:
   - vic-uni-book.lndo.site
services:
  database:
    creds:
      user: drupal9
      password: drupal9
      database: drupal9
